### ISSUE TITLE
YXX

### ISSUE THREAD

**Issue by ORSaeros** [lynnandtonic/airport-codes#393] opened 2015-03-28 13:34 UTC
YXX is Abbotsford International Airport serving the Fraser Valley area of Metro Vancouver.

**Comment by ORSaeros** [comment] 2015-03-28 13:35
Located in Abbotsford BC

**Comment by lynnandtonic** [comment] 2015-03-28 14:12
This is a duplicate of #221, closing this one. Thank you!

**Closed by lynnandtonic** 2015-03-28 14:12 UTC
