### ISSUE TITLE
AEP (Buenos Aires, Argentina)

### ISSUE THREAD

**Issue by francisco777** [lynnandtonic/airport-codes#526] opened 2015-04-01 19:35 UTC
AEP is Aeroparque Jorge Newbery, located in Buenos Aires, Argentina. Named after a famous Argentine aviator and serving Buenos Aires for domestic and regional commercial flights.

![aeroparque_jorge_newberry-overview_ by_dario_crusafon](https://cloud.githubusercontent.com/assets/11760226/6949826/a66bb568-d884-11e4-8eac-994b2ae77bef.jpg)

**Comment by ramiro** [comment] 2015-04-04 15:44
This is a duplicate of #235

**Comment by lynnandtonic** [comment] 2015-04-19 05:41
Thank you!

**Closed** 2015-04-19 05:40 UTC
