### ISSUE TITLE
YHZ (Enfield/Halifax, Nova Scotia, Canada) Robert L. Stanfield Int. Airport

### ISSUE THREAD

**Issue by peggykb9** [lynnandtonic/airport-codes#533] opened 2015-04-01 20:14 UTC
YHZ (Enfield/Halifax, Nova Scotia, Canada) Robert L. Stanfield International Airport

**Comment by lynnandtonic** [comment] 2015-04-20 03:06
This is a duplicate of #39, so closing this one. Thanks!

**Closed by lynnandtonic** 2015-04-20 03:06 UTC
Labels: duplicate
