### ISSUE TITLE
CDC and CPR

### ISSUE THREAD

**Issue by gcb5196** [lynnandtonic/airport-codes#900] opened 2016-02-18 08:57 UTC
CDC, Cedar City Utah
CPR, Casper Wyoming

**Comment by lynnandtonic** [comment] 2016-04-25 01:52
### CDC - Cedar CIty

Photo: https://flic.kr/p/5sWKGc

```
{
    "id": "cdc",
    "name": "Cedar City Regional Airport",
    "city": "Cedar City",
    "state": "Utah",
    "stateShort": "UT",
    "country": "USA",
    "description": "Cedar City Regional gets its three-letter airport code from its home in the city of *C*e*d*ar *C*ity, Utah.",
    "imageCredit": "g Tarded",
    "imageCreditLink": "https://www.flickr.com/photos/gtarded/"
}
```

**Comment by lynnandtonic** [comment] 2016-04-25 01:56
### CPR - Casper

- [ ]  Needs photo 

```
{
    "id": "cdc",
    "name": "Casper–Natrona County International Airport",
    "city": "Casper",
    "state": "Wyoming",
    "stateShort": "WY",
    "country": "USA",
    "description": "Opened in 1942, Casper–Natrona County International gets its three-letter code from its city of *C*as*p*e*r*, Wyoming.",
    "imageCredit": "g Tarded",
    "imageCreditLink": "https://www.flickr.com/photos/gtarded/"
}
```

**Comment by timothyubbens** [comment] 2018-10-08 02:32
2nd half of this issue is a duplicate of #945

**Comment by lynnandtonic** [comment] 2018-10-08 15:11
@timothyubbens Oh you're right. Good catch. Going to close this one in favor of that one. Thank you! 💃

**Closed by lynnandtonic** 2018-10-08 15:11 UTC
Labels: airport :airplane:, needs photo :camera_flash:
