### ISSUE TITLE
+YYT

### ISSUE THREAD

**Issue by github-alison** [lynnandtonic/airport-codes#558] opened 2015-04-02 04:30 UTC
YYT is St. John's International Airport in Newfoundland, Canada.  The "T" comes from it's original name which was Torbay Airport; Torbay is near St. John's.  The use of "T" also avoids confusion with St. John Airport (YSJ).  The airport officially opened in 1941, eight years before Newfoundland joined Confederation.

**Comment by lynnandtonic** [comment] 2015-04-02 04:39
This is a duplicate of #312. I'll close this one and copy your information there. Thank you, @github-alison! :+1:

**Closed** 2015-04-02 04:40 UTC
Labels: duplicate
