### ISSUE TITLE
KUF

### ISSUE THREAD

**Issue by Mokas-Uncle** [lynnandtonic/airport-codes#864] opened 2015-10-14 06:39 UTC
KUF is one of Russias top ten airports and serves the city of Samara on river Volga. It is named after the village of Kurumoch close to the airport - from which also the 3 letter code is derived.

https://en.wikipedia.org/wiki/Kurumoch_International_Airport
![kuf](https://cloud.githubusercontent.com/assets/15101875/10476537/081ac8b2-724f-11e5-9712-3406055a5b56.jpg)

**Comment by lynnandtonic** [comment] 2015-11-01 01:30
This is a duplicate of #662. I will be closing this one, but linking to your issue for future reference. Thank you, @Mokas-Uncle!

**Closed by lynnandtonic** 2015-11-01 01:30 UTC
